

#footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
robot_radius: 0.3

robot_base_frame: sonny/base
update_frequency: 0.5
publish_frequency: 2.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 2.5
raytrace_range: 3.5

inflation:
  inflation_radius: 0.01

static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: "sonny/laserFrame" , data_type: LaserScan, topic: "sonny/laser_scan", marking: true, clearing: true}
