obstacle_range: 3.0
raytrace_range: 3.5
#footprint: [[0.12, 0.14], [0.12, -0.14], [-0.12, -0.14], [-0.12, 0.14]]
subscribe_to_updates: true
robot_radius: 0.3
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: "sonny/base" , data_type: LaserScan, topic: "sonny/laser_scan", marking: true, clearing: true}
