

#footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
robot_radius: 0.3

robot_base_frame: base_link
update_frequency: 4.0 
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

inflation:
  inflation_radius: 1.0 

static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan,   marking: true, clearing: true, inf_is_valid: true}
