global_costmap:
  update_frequency: 2.0
  static_map: false 
  width: 15
  height: 15
  origin_x: -7.5
  origin_y: -7.5
  static_map: true
  rolling_window: true
  inflation_radius: 2.5
  resolution: 0.1
