local_costmap:
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  inflation_radius: 0.2
  width: 3
  height: 3
  origin_x: -1.5
  origin_y: -1.5
  resolution: 0.1
