local_costmap:
  global_frame: sonny/odomFrame 
  robot_base_frame: sonny/base
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  inflation_radius: 0.1
  width: 2
  height: 2
  origin_x: 0 
  origin_y: 0
  resolution: 0.05
